version: "1"
services:
  postgres:
    container_name: postgres
    build: ./postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    container_name: redis
    build: ./redis
    image: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  backend-service:
    container_name: backend-service
    build: ./backend
    image: backend-service
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
  shop-app:
    container_name: shop-app
    build: ./shop-app
    image: shop-app
    ports:
      - 80:5173
    depends_on:
      - backend-service