version: "1"
services:
  postgres:
    container_name: postgres
    build: ./postgres
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  redis:
    container_name: redis
    build: ./redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  shop-app-backend:
    container_name: shop-app-backend
    build: ./shop-app-backend
    image: shop-app-backend
    ports:
      - 8088:8088
    depends_on:
      - postgres
      - redis
  shop-app:
    container_name: shop-app
    build: ./shop-app
    image: shop-app
    ports:
      - 8080:8080
    depends_on:
      - shop-app-backend