version: "1"
services:
  postgres:
    build: ./postgresql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./:/docker-entrypoint-initdb.d/
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  backend-service:
    build: ./backend
    image: backend-service
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
  shop-app:
      build: ./shop-app
      image: shop-app
      ports:
        - 5173:5173
      depends_on:
        - backend-service