version: "1"
services:
  postgres:
    image: k9798909/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  backend-service:
    image: k9798909/backend-service
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
  shop-app:
      image: k9798909/shop-app
      ports:
        - 5173:5173
      depends_on:
        - backend-service