version: "1"
services:
  postgres:
    container_name: postgres
    image: k9798909/postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    container_name: redis
    image: k9798909/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  backend-service:
    container_name: backend-service
    image: k9798909/backend-service
    depends_on:
      - postgres
      - redis
  shop-app:
    container_name: shop-app
    image: k9798909/shop-app
    ports:
      - 8080:8080
    depends_on:
      - backend-service